apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak.conf: |
    # Basic settings for running in production. Change accordingly before deploying the server.

    # Database

    # The database vendor.
    db=postgres
    db-url-database=keycloak
    db-url-host=10.101.9.183
    db-url-port=5432
    # The username of the database user.
    db-username=keycloak_user

    # The password of the database user.
    db-password=keycloak123

    # The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
    #db-url=jdbc:postgresql://localhost/keycloak

    # Observability

    # If the server should expose healthcheck endpoints.
    #health-enabled=true

    # If the server should expose metrics endpoints.
    #metrics-enabled=true

    # HTTP

    # The file path to a server certificate or certificate chain in PEM format.
    #https-certificate-file=${kc.home.dir}conf/server.crt.pem

    # The file path to a private key in PEM format.
    #https-certificate-key-file=${kc.home.dir}conf/server.key.pem
