apiVersion: v1
kind: Service
metadata:
  namespace: keycloak
  name: keycloak-svc
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
